<?php

const DS = '/';
define('API_APP_ROOT', realpath(dirname(__FILE__)));

$dotenv = Dotenv\Dotenv::createImmutable(API_APP_ROOT, '.env');
$dotenv->load();

const APP_DIR = '';
const PUBLIC_PATH = API_APP_ROOT . DS . 'public';

define('URL', $_ENV['URL']);
define('APP_NAME', $_ENV['APP_NAME']);
define('PORTAL_URL', $_ENV['PORTAL_URL']);
define('API_URL', $_ENV['API_URL']);
define('API_BACKEND_URL', $_ENV['API_BACKEND_URL']);
define('API_PORTAL_URL', $_ENV['API_PORTAL_URL']);

define('ATTACHMENT_URL', $_ENV['ATTACHMENT_URL']);

define('APP_KEY', $_ENV['APP_KEY']);
define('PASS_SALT', $_ENV['PASS_SALT']);
define('PIN_SALT', $_ENV['PIN_SALT']);

define('HASH_ALGO', $_ENV['HASH_ALGO']);
define('MX_SMS_SENDER_ID', $_ENV['MX_SMS_SENDER_ID']);
define('MX_SMS_CAMPAIGN', $_ENV['MX_SMS_CAMPAIGN']);

define('MAILGUN_API_KEY', $_ENV['MAILGUN_API_KEY']);
define('MAILGUN_API_HOSTNAME', $_ENV['MAILGUN_API_HOSTNAME']);
define('MAILGUN_DOMAIN', $_ENV['MAILGUN_DOMAIN']);

//test from arrival

// test
define('CYBERSOURCE_PAYMENT_SECRET_KEY', $_ENV['CYBERSOURCE_PAYMENT_SECRET_KEY']);
define('CYBERSOURCE_PAYMENT_ACCESS_KEY', $_ENV['CYBERSOURCE_PAYMENT_ACCESS_KEY']);
define('CYBERSOURCE_PAYMENT_PROFILE_ID', $_ENV['CYBERSOURCE_PAYMENT_PROFILE_ID']);
define('CYBERSOURCE_PAYMENT_CURRENCY', $_ENV['CYBERSOURCE_PAYMENT_CURRENCY']);
define('CYBERSOURCE_MERCHANT_ID', $_ENV['CYBERSOURCE_MERCHANT_ID']);
define('CYBERSOURCE_PAYMENT_SEARCH_API_KEY', $_ENV['CYBERSOURCE_PAYMENT_SEARCH_API_KEY']);
define('CYBERSOURCE_PAYMENT_SEARCH_SECRET_KEY', $_ENV['CYBERSOURCE_PAYMENT_SEARCH_SECRET_KEY']);
define('CYBERSOURCE_PAYMENT_SEARCH_URL', $_ENV['CYBERSOURCE_PAYMENT_SEARCH_URL']);
define('CYBERSOURCE_PAYMENT_HOST_API_URL', $_ENV['CYBERSOURCE_PAYMENT_HOST_API_URL']);
define('CYBERSOURCE_PAYMENT_URL', $_ENV['CYBERSOURCE_PAYMENT_URL']);
define('CYBERSOURCE_PAYMENT_LOCALE', $_ENV['CYBERSOURCE_PAYMENT_LOCALE']);

define('CRDB_CARD_ONLINE_TZS', "14");
define('CRDB_CARD_ONLINE_USD', "3");

define('NMB_CARD_ONLINE_TZS', "14");
define('NMB_CARD_ONLINE_USD', "3");

define('TZS', "1");
define('USD', "2");

define('NMB_MERCHANT_ID', $_ENV['NMB_MERCHANT_ID']);
define('NMB_PASSWORD', $_ENV['NMB_PASSWORD']);
define('NMB_URL', $_ENV['NMB_URL']);

define('SELCOME_URL', $_ENV['SELCOME_URL']);
define('SELCOME_REDIRECT_URL', $_ENV['SELCOME_REDIRECT_URL']);
define('SELCOME_CANCEL_URL', $_ENV['SELCOME_CANCEL_URL']);
define('SELCOME_CALLBACK_URL', $_ENV['SELCOME_CALLBACK_URL']);
define('SELCOME_VENDOR', $_ENV['SELCOME_VENDOR']);
define('SELCOME_API_KEY', $_ENV['SELCOME_API_KEY']);
define('SELCOME_SECRET_KEY', $_ENV['SELCOME_SECRET_KEY']);